/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _publicIndexRouteImport } from './routes/__public/index'
import { Route as _authorizeProfileRouteImport } from './routes/__authorize/profile'

const _publicIndexRoute = _publicIndexRouteImport.update({
  id: '/__public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _authorizeProfileRoute = _authorizeProfileRouteImport.update({
  id: '/__authorize/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/profile': typeof _authorizeProfileRoute
  '/': typeof _publicIndexRoute
}
export interface FileRoutesByTo {
  '/profile': typeof _authorizeProfileRoute
  '/': typeof _publicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__authorize/profile': typeof _authorizeProfileRoute
  '/__public/': typeof _publicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/profile' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/profile' | '/'
  id: '__root__' | '/__authorize/profile' | '/__public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authorizeProfileRoute: typeof _authorizeProfileRoute
  _publicIndexRoute: typeof _publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__public/': {
      id: '/__public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authorize/profile': {
      id: '/__authorize/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof _authorizeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _authorizeProfileRoute: _authorizeProfileRoute,
  _publicIndexRoute: _publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
