/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _publicIndexRouteImport } from './routes/__public/index'
import { Route as _publicRegisterRouteImport } from './routes/__public/register'
import { Route as _publicLoginRouteImport } from './routes/__public/login'
import { Route as _authorizeProfileRouteImport } from './routes/__authorize/profile'
import { Route as _authorizeDashboardRouteImport } from './routes/__authorize/dashboard'

const _publicIndexRoute = _publicIndexRouteImport.update({
  id: '/__public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicRegisterRoute = _publicRegisterRouteImport.update({
  id: '/__public/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const _publicLoginRoute = _publicLoginRouteImport.update({
  id: '/__public/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authorizeProfileRoute = _authorizeProfileRouteImport.update({
  id: '/__authorize/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const _authorizeDashboardRoute = _authorizeDashboardRouteImport.update({
  id: '/__authorize/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof _authorizeDashboardRoute
  '/profile': typeof _authorizeProfileRoute
  '/login': typeof _publicLoginRoute
  '/register': typeof _publicRegisterRoute
  '/': typeof _publicIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof _authorizeDashboardRoute
  '/profile': typeof _authorizeProfileRoute
  '/login': typeof _publicLoginRoute
  '/register': typeof _publicRegisterRoute
  '/': typeof _publicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/__authorize/dashboard': typeof _authorizeDashboardRoute
  '/__authorize/profile': typeof _authorizeProfileRoute
  '/__public/login': typeof _publicLoginRoute
  '/__public/register': typeof _publicRegisterRoute
  '/__public/': typeof _publicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/profile' | '/login' | '/register' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/profile' | '/login' | '/register' | '/'
  id:
    | '__root__'
    | '/__authorize/dashboard'
    | '/__authorize/profile'
    | '/__public/login'
    | '/__public/register'
    | '/__public/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  _authorizeDashboardRoute: typeof _authorizeDashboardRoute
  _authorizeProfileRoute: typeof _authorizeProfileRoute
  _publicLoginRoute: typeof _publicLoginRoute
  _publicRegisterRoute: typeof _publicRegisterRoute
  _publicIndexRoute: typeof _publicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__public/': {
      id: '/__public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof _publicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public/register': {
      id: '/__public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof _publicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__public/login': {
      id: '/__public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authorize/profile': {
      id: '/__authorize/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof _authorizeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authorize/dashboard': {
      id: '/__authorize/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _authorizeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  _authorizeDashboardRoute: _authorizeDashboardRoute,
  _authorizeProfileRoute: _authorizeProfileRoute,
  _publicLoginRoute: _publicLoginRoute,
  _publicRegisterRoute: _publicRegisterRoute,
  _publicIndexRoute: _publicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
